### ISSUE TITLE
No workspaces found

### ISSUE THREAD

**Issue by qkdreyer** [sadesyllas/vscode-workspace-switcher#13]
Not sure what I'm doing wrong but I'm keep getting "No workspaces found" while using "Switch workspace..." command

**Comment by sadesyllas** [comment]
This message means that no `.code-workspace` files were found by the extension.

These files are looked up in the directories denoted by the `vscodeWorkspaceSwitcher.paths` configuration property.

Has this been set?

**Comment by sadesyllas** [comment]
Please, re-open if this issue still applies.

**Comment by rockintech88** [comment]
vscodeWorkspaceSwitcher.paths is configured in my user settings.  It is a list of folders which contain the .code-workspace files. my user settings json file contains:

```
"vscodeWorkspaceSwitcher.paths": [
    "/prj/chipsandcheese/statenA/",
    "/prj/chipsandcheese/statenB/"
],

```

and I have:
/prj/chipsandcheese/statenA/.code-workspace
/prj/chipsandcheese/statenB/.code-workspace

but when I try to switch workspaces, I keep getting the same error "No workspaces found"
