### ISSUE TITLE
Issues when the workspaces directory is a symlink

### ISSUE THREAD

**Issue by ehmicky** [sadesyllas/vscode-workspace-switcher#15]
Directories in `vscodeWorkspaceSwitcher.paths` are skipped if they are a symlink, which is probably a bug. This is because of [using `fs.lstat()`](https://github.com/sadesyllas/vscode-workspace-switcher/blob/master/src/extension.ts#L203) instead of `fs.stat()`.

For information, my workspaces directory is symlinked to a separate partition that is backed up from times to times.

**Comment by sadesyllas** [comment]
Please, update to [v1.10.2](https://github.com/sadesyllas/vscode-workspace-switcher/releases/tag/v1.10.2).

`fs.statSync` is now being used and symlinks should work as expected.

**Comment by ehmicky** [comment]
Thanks this works!
