### ISSUE TITLE
Feature Request: UI

### ISSUE THREAD

**Issue by joezimdelta** [sadesyllas/vscode-workspace-switcher#16]
This isn't a big deal but I thought I'd bring it up just in case it's something you'd like to do. I switched to this plugin from the [Project Manager](https://marketplace.visualstudio.com/items?itemName=alefragnani.project-manager) plugin because it didn't support the workspace files and I prefer to use them. One nice thing PM had was a sidebar UI, so that when I happened to be using my mouse already, I could use that instead of switching to keyboard and using shortcuts. I was curious if you'd consider doing something similar? You may not even need to do a sidebar. You could instead write something in the footer indicating the open workspace name and be able to click it to bring up the list of workspaces to switch to.

Once again, this is just food for thought. I'm sure most devs are ok with sticking to the keyboard navigation.

**Comment by sadesyllas** [comment]
Thanks, It's a great idea!

As I see it, there are two main options here, a `Tree View Container` (ie, the thing on the left like `Debug` and `Extensions`) and/or a `Tree View` (ie, like the open files tree view in the top-most `Tree View Container`).

I will consider these options and see what I can do with them.

**Comment by sadesyllas** [comment]
This has been implemented in v1.11.0.

Thanks for the idea!
