### ISSUE TITLE
UNRESPONSIVE extension host 'sadesyllas.vscode-workspace-switcher'

### ISSUE THREAD

**Issue by MarcPer** [sadesyllas/vscode-workspace-switcher#17]
The time it takes for the list of workspaces to show up after the _Switch workspace_ command is called has increased significantly (it is taking 6s now, whereas it used to be almost instantaneous).

I see this in the developer console:
```
UNRESPONSIVE extension host, 'sadesyllas.vscode-workspace-switcher' took 97% of 5149.959ms...
```

Info about my running visual studio code:
```
Version: 1.32.3
Commit: a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4
Date: 2019-03-14T23:38:49.842Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.15.0-46-generic
```

Let me know if I can provide more information.

**Comment by andrewmassengale** [comment]
Mine is completely unresponsive. It's killing the extensionHost.

```
==== JS stack trace =========================================

Security context: 0x2b6bbb8a5709 <JSObject>
    0: builtin exit frame: new Error(this=0,0x2b6bf4d674d9 <String[32]: Cannot find module 'ansi-yellow'>,0)

    1: StubFrame [pc: 0x5580c28bc1d]
    2: n [~/.vscode/extensions/sadesyllas.vscode-workspace-switcher-1.10.2/dist/extension.js:245] [bytecode=0x2b6bc21fc1b9 offset=26](this=0x2b6b67004311 <JSGlobal Object>,t=0x2b6bc21d9dc1 <String[11]: ansi-yellow>)
    3: /* anonymous */...
```

**Comment by MarcPer** [comment]
I just learned visual studio has a built-in `File: Open Recent...` command (shortcut is _Ctrl+R_ for me) that works also for switching workspaces, so this extension might not be needed anymore.

**Comment by sadesyllas** [comment]
A recent update to the extension has been to allow symlinks when searching for workspace files.

If you have the time could answer/try the following?

1. Could it be that you are using a symlink somewhere under your workspace root folder (the one set in the extension configuration) and there is a cycle when trying to find all workspace files?
2. If that is not the case, does removing the extension and re-installing it work?

**Comment by MarcPer** [comment]
1. That is not the case
2. Re-installing doesn't help.

I have multiple paths on `vscodeWorkspaceSwitcher.paths` and I could see that each added path increases the time noticeably. Some directories there have a dozen of workspaces, but I tried also using a single path where there are just a couple of workspaces and it is still slow.

**Comment by okgolove** [comment]
Same problem.

**Comment by sadesyllas** [comment]
OK, I found the time to reproduce it so I will do some more digging.

**Comment by sadesyllas** [comment]
Please, update to v1.10.3 and tell me if this continues.

There was definitely a problem introduced by the new way of bundling the extension code using webpack, which was caused by `glob-fs`.

I updated my dependencies to use `fast-glob` and I can no longer reproduce it.

**Comment by okgolove** [comment]
@sadesyllas now it works properly. Thank you for your extension!

**Comment by sadesyllas** [comment]
@okgolove, you are welcome!
