### ISSUE TITLE
Doesn't globs into subdirectory and Symbolic Link

### ISSUE THREAD

**Issue by anishmittal2020** [sadesyllas/vscode-workspace-switcher#19]
In my settings `"vscodeWorkspaceSwitcher.paths": "/home/nikhil/Documents/Git/CS/**/*"`, does not finds the workspace files in the subdirectory. `fast-glob` supports this type of input.

**Comment by anishmittal2020** [comment]
@sadesyllas  I just noticed that most of my `.code-workspace` files are symbolic link. But the glob does not recognize them.

**Comment by sadesyllas** [comment]
Please, try v1.10.4 report whether this has been fixed or not.

**Comment by anishmittal2020** [comment]
Hi it works. Somehow it is taking a lot of time. I have about 30 symlinked workspaces. Is it slow due to symlink?

**Comment by sadesyllas** [comment]
@anishmittal2020, to answer that I would need to know more about whether or not you have eg, cycles where one symlink points to another and things like that.

What do you mean by `a lot of time`?

**Comment by sadesyllas** [comment]
I am closing this as it's no longer relevant to the issue's topic.

Please, re-open it if you have more information or open another one describing what exactly goes wrong and an example setup where the extension is slow.

Thank you for your help catching this bug!
