### ISSUE TITLE
No workspaces found : Configuration problem ?

### ISSUE THREAD

**Issue by gvigner** [sadesyllas/vscode-workspace-switcher#2]
I can't make it work: "**Info** No workspaces found"

Below is my **USER SETTINGS** :
```
{
    "remote.onstartup": true,
    "explorer.confirmDelete": false,

    "emmet.includeLanguages": {
        "blade": "html"
    },
    "emmet.triggerExpansionOnTab": true,
    "vscodeWorkspaceSwitcher.paths": [
        "~/code/blog/blog.code-workspace",
        "~/code/sysorkspace/myws.code-workspace"
    ]
}
```

Anything wrong with it ?

**Comment by sadesyllas** [comment]
Hi @gvigner!

The `vscodeWorkspaceSwitcher.paths` variable is for an array of paths to **folders** containing `.code-workspace` files.

So, in your example it would be:
```javascript
{
    "vscodeWorkspaceSwitcher.paths": [
        "~/code/blog",
        "~/code/sysorkspace"
    ]
}
```

**Comment by gvigner** [comment]
Ok, I changed it to this:
```
{
    "remote.onstartup": true,
    "explorer.confirmDelete": false,

    "emmet.includeLanguages": {
        "blade": "html"
    },
    "vscodeWorkspaceSwitcher.paths": [
        "~/code/blog",
        "~/code/myworkspace"
    ]
}
```
But I still get the message: "**Info** No workspaces found" when I press **control-k w**

**Comment by sadesyllas** [comment]
Can you please try using absolute paths?

And what platform are you using?

**Comment by gvigner** [comment]
I'm using Code 1.18.1 on OSX 10.13.1.
I tried with absolute path, still not working.

**Comment by sadesyllas** [comment]
@gvigner, I'll try testing on osx because I don't have access to it right now and get back to you.

**Comment by gvigner** [comment]
Thank you

**Comment by simnom** [comment]
Just a note on this using the shorthand home locator doesn't appear to work, however changing to an absolute path does.  For example:

```
"vscodeWorkspaceSwitcher.paths": [
    "~/Documents/vscode-workspaces"
]
```
**Result**: No workspaces found

```
"vscodeWorkspaceSwitcher.paths": [
    "/Users/username/Documents/vscode-workspaces"
]
```
**Result:** Lists my available workspaces

MacOS: 10.13.1

**Comment by whitevo** [comment]
same problem cant find location
`{
    "workbench.colorTheme": "Monokai",
    "workbench.iconTheme": "Monokai Pro (Filter Spectrum) Icons",
    "workbench.startupEditor": "newUntitledFile",

    "[yaml]": {
        "editor.insertSpaces": true,
        "editor.tabSize": 4
    },
    "git.ignoreMissingGitWarning": true,

	"vscodeWorkspaceSwitcher.paths": [
		"C:\Users\whitevo\Desktop\Whi World\Whi World"
	],
}   `

**Comment by ugurozturk** [comment]
@whitevo use "\\" insted "\"

**Comment by whitevo** [comment]
I did, still didn''ät work.

**Comment by whitevo** [comment]
Ah I figured it out.
I changed the shortcut settings to ctrl+s, before I saved the user settings.
which caused the error comes before saving the user settings and the error caused not to save it either.

**Comment by whitevo** [comment]
well nvm it still gives error that command failed and shows correct path and file name

**Comment by whitevo** [comment]
doesn't matter anymore, uninstalled don't have time for this.

**Comment by ugurozturk** [comment]
@whitevo You can't say that in github. Every line code his made is honorable. If you think this repo is not working than do PR! yet i can't see any coded line on your github account to anywhere.

**Comment by Gigacee** [comment]
Insert this to L115 of extension.js, so relative path will become valid.

```javascript
    for (var i = 0; i < paths.length; i++) {
        paths[i] = paths[i].replace('~', userHome);
    }
```

**Comment by Gigacee** [comment]
Sorry, I can't use TypeScript...

**Comment by ugurozturk** [comment]
@Gigacee why dont pr but comment

**Comment by Gigacee** [comment]
Is this code right on .ts?

**Comment by Gigacee** [comment]
I did it! Is this OK?
#6

**Comment by ugurozturk** [comment]
@Gigacee Yeah now the repo owner can test it

**Comment by Gigacee** [comment]
@ugurozturk Thank you for your advice!

**Comment by sadesyllas** [comment]
@Gigacee, @ugurozturk, thank you for contribution. I'll check the PR today. 😃

**Comment by sadesyllas** [comment]
Hi everyone!
Obviously I did not find the time to check the PR when I said I would 😞 but "never late than never"...
It has been merged.
@Gigacee, thanks for contributing!
@ugurozturk, thanks for your support in the comments above!

**Comment by shivapoudel** [comment]
@sadesyllas How to do this for iCloud folder content path as `Mobile Documents` has a space on mac.

`/Users/shivapoudel/Library/Mobile Documents/com~apple~CloudDocs/Workspace`
