### ISSUE TITLE
Duplicate entries

### ISSUE THREAD

**Issue by troychaplin79** [sadesyllas/vscode-workspace-switcher#20]
When I bring up my list of saved workspaces I now see duplicate entries for each saved workspace. Pretty sure this started after the commit from this morning, I didn't have any issues yesterday.

**Comment by johnpicozzi** [comment]
I noticed this as well.

**Comment by sadesyllas** [comment]
Please, try v1.10.5. This should be fixed.

**Comment by troychaplin79** [comment]
Thanks for the quick update @sadesyllas, this fixes the issue

**Comment by johnpicozzi** [comment]
Works Thanks! Will note for anyone else that has this issue. You may need to disable and re-enable to fix the issue.
