### ISSUE TITLE
Duplicated paths

### ISSUE THREAD

**Issue by andremiguelaa** [sadesyllas/vscode-workspace-switcher#21]
I started to get duplicated paths when I'm trying to save a workspace.

<img width="632" alt="Screenshot 2019-03-28 at 12 18 23" src="https://user-images.githubusercontent.com/1964691/55157163-a8f0ce80-5153-11e9-894b-189c5c6cda4d.png">

**Comment by sadesyllas** [comment]
This has been fixed in v1.12.1.

Thank you for reporting this!

**Comment by andremiguelaa** [comment]
You're welcome ;)
Thanks for the great work!
