### ISSUE TITLE
Feature Request: Folder structure in Activity Bar

### ISSUE THREAD

**Issue by apalfrey** [sadesyllas/vscode-workspace-switcher#22]
I have the folder I keep my `.code-workspace` files in structured depending on the type of work (`/Libraries` for any libraries, `/Work` for any jobs etc.)

I have the paths set to `C:\\dev\\vscode-projects\\**\\*` and was wondering if it is possible that they could be displayed in the activity bar panel with the folder structure e.g. any workspaces under `C:\dev\vscode-projects\Libraries` would be under a section called `Libraries`, workspaces under `C:\dev\vscode-projects\Work` would be under a section called `Work` etc.

**Comment by sadesyllas** [comment]
This is a great idea! :slightly_smiling_face: 

I will try to find the time to implement it.

Of course, this also means buttons for `expand all` and `collapse all` functionality, etc.

**Comment by sadesyllas** [comment]
Please, checkout version v1.15.0 and reopen this if need be.

Thank you very much for your feedback!

**Comment by apalfrey** [comment]
That seems to have worked after changing the paths to just `C:\\dev\\vscode-projects\\**` instead of `C:\\dev\\vscode-projects\\**\\*`. Thank you very much. I'll keep checking it out and let you know if I have any problems :smile:
