### ISSUE TITLE
code-server support

### ISSUE THREAD

**Issue by nhooyr** [sadesyllas/vscode-workspace-switcher#28]
Hi @sadesyllas, a user reported that this extension does not work with code-server.

It seems to spawn `code` directly instead of using the VS Code API.

Details at https://github.com/cdr/code-server/issues/1121

Opening this to track this here instead of in the code-server repo.

**Comment by axiac** [comment]
[This duff](https://github.com/sadesyllas/vscode-workspace-switcher/compare/master...axiac:vscode-api-load?expand=1) contains the minimum amount of changes required to fix this issue.
I tested them on macOS and they work fine.

**Comment by sadesyllas** [comment]
In v1.15.0 this issue has been fixed.

@nhooyr, thank you very much for bringing this to my attention!

@axiac, thank you very much for your PR but I checked it out after I had fixed the problem so I ended up applyin pretty much the same changes like the ones you proposed, as part of fixing #31.
