### ISSUE TITLE
Command failed: code -r

### ISSUE THREAD

**Issue by dougkozar** [sadesyllas/vscode-workspace-switcher#31]
Command failed: code -r "/users/dougkozar/Visual Studio Code Workspaces/knownhost.code-workspace" /bin/sh: code: command not found

What am I doing wrong here? Thanks!

![Screen Shot 2020-07-08 at 10 49 37 AM](https://user-images.githubusercontent.com/14360071/86937922-d32e8b80-c10d-11ea-82ea-2fb74bfe9269.png)

**Comment by sadesyllas** [comment]
Please, upgrade to v1.15.0 where this issue has been fixed.

Thank you for your feedback!
