### ISSUE TITLE
Please list the actual command names in the README

### ISSUE THREAD

**Issue by cb109** [sadesyllas/vscode-workspace-switcher#32]
It seems some commands have been changed from e.g. `vscodeWorkspaceSwitcher.switchWorkspace` to `vscodeWorkspaceSwitcher.openWorkspace` and that broke my custom keybindings. It would have been easier to fix this on my side were the commands listed in the README.

Thanks for the extension, much appreciated!

**Comment by sadesyllas** [comment]
Thank you for reporting this!

I have corrected the relevant text in the README in v1.15.3.
