### ISSUE TITLE
Save not working

### ISSUE THREAD

**Issue by chavlji** [sadesyllas/vscode-workspace-switcher#33]
I have latest VSC installed and latest version of the app. If I run "cmd+shift+p" "save workspace" it shows me the input at the top. I enter new workspace name and press enter... and nothing happens?! How to fix this?

**Comment by sadesyllas** [comment]
I cannot reproduce this.

What OS are you using and could you please try the `W` icon on the vertical bar, to the left (ie, the activity bar)?

There, you should find the "Save Workspace" button on the top (shaped like a box with an arrow pointing inside it).

**Comment by chavlji** [comment]
I'm sorry for the false alarm...
I must have started writing a new workflow name in the first field where you're supposed to select the folder 🤦 
It works great now!
