### ISSUE TITLE
Publish Extension on OpenVSX

### ISSUE THREAD

**Issue by SimonBrazell** [sadesyllas/vscode-workspace-switcher#36]
Hello, this extension is really handy, I wonder if you would consider also publishing it to OpenVSX, the vendor neutral open source alternative to the Visual Studio Marketplace?

Instructions on how to do so are found [here](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions).

Cheers!

**Comment by sadesyllas** [comment]
Thanks for this suggestion! I will look into it.

**Comment by sadesyllas** [comment]
It's done: https://open-vsx.org/extension/sadesyllas/vscode-workspace-switcher. :slightly_smiling_face:

**Comment by SimonBrazell** [comment]
Awesome! I'll give it a try tomorrow 🙂
