### ISSUE TITLE
path on mac

### ISSUE THREAD

**Issue by jw-miaem** [sadesyllas/vscode-workspace-switcher#4]
Hi, 
Great idea and could do with this to organise my workspaces. However I keep getting a failed message when trying to switch workspaces:
Command failed: code -r <file path>
I'm on mac and storing workspaces on external drive, which is showing up in the switcher so appears to work but not when opening workspaces. Also code is in $PATH

**Comment by jowoo** [comment]
turns out it doesn't work with external drive as works fine with local workspaces

**Comment by sadesyllas** [comment]
Hi @jw-miaem, I just found time to show this project some love again, so please provide an example path for me to try with (you mentioned something about '()' in the path).

I don't own a mac so please provide as much info as you can, e.g., in the developer console, what other info is there about `code -r` failing to run?

**Comment by jw-miaem** [comment]
Hi @sadesyllas I've stopped using vscode for now but the problem stemmed from me storing projects on an external drive. The file path had special characters '()' in and they seemed to break the functionality. I think this should be testable on windows etc...

**Comment by sadesyllas** [comment]
@jw-miaem, as per #7 I had a 😢 omission of quotes around workspace paths.

Perhaps, v1.5.1 solves the problem you encountered as well.

**Comment by jw-miaem** [comment]
pretty sure that will fix it so closing :relaxed:

**Comment by janbaykara** [comment]
I'm getting the same error on Mac. Storing vscode workspaces in `~/Documents` and getting the following error:

```
Command failed: code -r "/Users/Jan/Documents/Dev/VSCodeWorkspaces/gyana.code-workspace" /bin/sh: code: command not found
```

**Comment by jw-miaem** [comment]
I think having code in your $PATH is a dependency of this plugin

**Comment by mike-code** [comment]
You can always do `udo ln -s /Applications/Visual\ Studio\ Code.app/Contents/Resources/app/bin/code /usr/local/bin/code`
