### ISSUE TITLE
Worspace load fails

### ISSUE THREAD

**Issue by lukaszlukasiewicz** [sadesyllas/vscode-workspace-switcher#5]
I get this message when I try to save or switch workspace:

> Command failed: code -r D:\vs-code-workspaces\test.code-workspace

But workspace files are saved and they are correct (normal open wokspace command works). 

Info from developer console:
> Command failed: code -r D:\code_ws\test.code-workspace
> D:\code_ws\test.code-workspace:1
> (function (exports, require, module, __filename, __dirname, process, global, Buffer) { return function (exports, require, module, __filename, __dirname) { {"folders":[{"path":"e:\\test"}],"settings":{}}
>                                                                                                                                                                      ^
> SyntaxError: Unexpected token :
> 
>     at createScript (vm.js:53:10)
>     at Object.runInThisContext (vm.js:95:10)
>     at Module._compile (module.js:543:28)
>     at Object.Module._extensions..js (module.js:580:10)
>     at Module.load (module.js:488:32)
>     at tryModuleLoad (module.js:447:12)
>     at Function.Module._load (module.js:439:3)
>     at Module.require (module.js:498:17)
>     at Function.Module._preloadModules (module.js:665:12)
>     at preloadModules (bootstrap_node.js:404:38)

Windows 10, 
VSCode 1.18.1. 
Plugin ver: 1.4.0

**Comment by rnyberg** [comment]
Same here. Works with code-insiders, but with regular code the switch fails.

**Comment by ugurozturk** [comment]
@lukaszlukasiewicz @rnyberg  check that. https://github.com/sadesyllas/vscode-workspace-switcher/issues/1

**Comment by rnyberg** [comment]
Yeah, `"vscodeWorkspaceSwitcher.codeExecutable": "C:\\Program Files\\Microsoft VS Code\\bin\\code.cmd",`  in my settings worked.

**Comment by sadesyllas** [comment]
@lukaszlukasiewicz, has the above proposed solution worked for you?

**Comment by lukaszlukasiewicz** [comment]
Yes it does. Sorry about the delay. 
After adding this path to the settings: 
`"vscodeWorkspaceSwitcher.codeExecutable" : "C:\\Program Files (x86)\\Microsoft VS Code\\bin\\code.cmd",`
It started working.
